# make a container of the required tools
version: "3.7"
services:
  mysql:
    image: quay.io/debezium/example-mysql:2.3
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=user123

  zookeeper:
    image: quay.io/debezium/zookeeper:2.3
    container_name: zookeeper
    ports:
      - 2181:2181

  kafka:
    image: quay.io/debezium/kafka:2.3
    container_name: kafka
    ports:
      - 9092:9092
    environment:
       ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  debezium:
    image: quay.io/debezium/connect:2.3
    container_name: debezium
    ports:
      - 8083:8083

    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      STATUS_STORAGE_TOPIC: my_connect_statuses

    depends_on:
      - kafka
      - mysql
