# make a container of the required tools
version: "3.7"
services:
  mysql:
    image: quay.io/debezium/example-mysql:2.3
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=user123

  zookeeper:
    image: quay.io/debezium/zookeeper:2.3
    container_name: zookeeper
    ports:
      - 2181:2181

  kafka:
    image: quay.io/debezium/kafka:2.3
    container_name: kafka
    ports:
      - 29092:29092
    environment:
      ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://:9092,EXTERNAL://:29092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    depends_on:
      - zookeeper

  debezium:
    image: quay.io/debezium/connect:2.3
    container_name: debezium
    ports:
      - 8083:8083

    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      STATUS_STORAGE_TOPIC: my_connect_statuses

    depends_on:
      - kafka
      - mysql
