# make a container of the required tools
version: "3.7"
services:
  mysql:
    image: "debezium/example-mysql:2.3"
    ports:
      -3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_USER=arkan
      - MYSQL_PASSWORD=123

      